POST http://localhost:3000/api/auth/signup
content-type: application/json

{
    "name": "André",
    "email": "andre.torbitoni@gmail.com",
    "password": "password"
}
###
POST http://localhost:3000/api/auth/signin
content-type: application/json

{
    "email": "andre.torbitoni@gmail.com",
    "password": "password"
}
###


GET http://localhost:3000/api/users/me
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZTRmZjMzYjIzODdkNzU2NDcyYzAxZWQiLCJyb2xlIjoidXNlciIsIm5hbWUiOiJBbmRyw6kiLCJleHAiOjE1ODc0ODQ3NDguMTQsImlhdCI6MTU4MjMwMDc0OH0.TFPBe9WsJsfIK71EncdrYLWLQGr_DLO9u5Gyhv720Dw
content-type: application/json

###
